# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thinroute < Formula
  desc "A local-first, OpenAI-compatible LLM gateway"
  homepage "https://github.com/0xfig-labs/thinroute"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0xfig-labs/thinroute/releases/download/v0.1.1/thinroute_0.1.1_darwin_amd64.tar.gz"
      sha256 "e1220e613d0b2af5c71fe6ab51d98c9bbf06bbee6d803422071640bf4358ccac"

      define_method(:install) do
        bin.install "thinroute"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0xfig-labs/thinroute/releases/download/v0.1.1/thinroute_0.1.1_darwin_arm64.tar.gz"
      sha256 "6c8ce25de5bef16e77a5ae487be2dd406e0ad4c0b3ad5a29cd83425dbf0df2c9"

      define_method(:install) do
        bin.install "thinroute"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xfig-labs/thinroute/releases/download/v0.1.1/thinroute_0.1.1_linux_amd64.tar.gz"
      sha256 "22c9909dae00443a1c3b9db4ce9f376814e9349b43c8ecc733a42397a115f429"
      define_method(:install) do
        bin.install "thinroute"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xfig-labs/thinroute/releases/download/v0.1.1/thinroute_0.1.1_linux_arm64.tar.gz"
      sha256 "ec1e9c23155e499b62c6c75e5e382d581ba5183625c0c501cc741aaad96d3133"
      define_method(:install) do
        bin.install "thinroute"
      end
    end
  end
end
