# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thinroute < Formula
  desc "A local-first, OpenAI-compatible LLM gateway"
  homepage "https://github.com/0xfig-labs/thinroute"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0xfig-labs/thinroute/releases/download/v0.1.7/thinroute_0.1.7_darwin_amd64.tar.gz"
      sha256 "576bf85220e488a040d158367331c6e054450d95759ac6de3deecb32e8969778"

      define_method(:install) do
        bin.install "thinroute"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0xfig-labs/thinroute/releases/download/v0.1.7/thinroute_0.1.7_darwin_arm64.tar.gz"
      sha256 "abe978721a71960402fb84ad2f34ab7855583a156f4231ad8cec7815a47610cd"

      define_method(:install) do
        bin.install "thinroute"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xfig-labs/thinroute/releases/download/v0.1.7/thinroute_0.1.7_linux_amd64.tar.gz"
      sha256 "349a9a010bbc05fd1dccc939d094f17e62fbb52ab106ad1fdf6a8f21ba88ab02"
      define_method(:install) do
        bin.install "thinroute"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xfig-labs/thinroute/releases/download/v0.1.7/thinroute_0.1.7_linux_arm64.tar.gz"
      sha256 "24b7d21425cfb6c303886e996a77b21e5616505de11a8adaf758657687e0d833"
      define_method(:install) do
        bin.install "thinroute"
      end
    end
  end
end
