# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Thinroute < Formula
  desc "A local-first, OpenAI-compatible LLM gateway"
  homepage "https://github.com/0xfig-labs/thinroute"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0xfig-labs/thinroute/releases/download/v0.1.6/thinroute_0.1.6_darwin_amd64.tar.gz"
      sha256 "4354b7428837f075e01d1798c80b03be7d8e43007abdceccdbe5e99d12dec0ca"

      define_method(:install) do
        bin.install "thinroute"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0xfig-labs/thinroute/releases/download/v0.1.6/thinroute_0.1.6_darwin_arm64.tar.gz"
      sha256 "f77d61ea687a9b96d896ebd5c9a9b5fb74007452c2fe266884f15ead5246d189"

      define_method(:install) do
        bin.install "thinroute"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xfig-labs/thinroute/releases/download/v0.1.6/thinroute_0.1.6_linux_amd64.tar.gz"
      sha256 "de24f387cc4c56d11c6e6496029e5a2e8ef1eb3daca63596670a8dc375a38381"
      define_method(:install) do
        bin.install "thinroute"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xfig-labs/thinroute/releases/download/v0.1.6/thinroute_0.1.6_linux_arm64.tar.gz"
      sha256 "c697b2152340f3cb019a5230e2e6e9a0f44cc3734303baba1ab7c5b5e6b59bf8"
      define_method(:install) do
        bin.install "thinroute"
      end
    end
  end
end
